name: LeaderOS
authors: [leaderos]
main: net.leaderos.plugin.Bukkit
version: '${shared.version}'
api-version: 1.13
folia-supported: true
softdepend: [PlaceholderAPI]
libraries:
    - org.hibernate.orm:hibernate-hikaricp:7.2.1.Final
    - org.hibernate.orm:hibernate-core:7.2.1.Final
    - org.hibernate.orm:hibernate-community-dialects:7.2.1.Final
    - com.h2database:h2:2.4.240
    - org.hsqldb:hsqldb:2.7.4
    - org.xerial:sqlite-jdbc:3.51.1.0
    - org.mariadb.jdbc:mariadb-java-client:3.5.3
    - mysql:mysql-connector-java:8.0.33
commands:
    leaderos:
        description: Default command of leaderos
    webstore:
        description: WebStore module default command
    credits:
        description: Credits module command
    creditvoucher:
        description: Voucher module command
    bazaar:
        description: bazaar default command
    discord-sync:
        description: Sync your account with discord
    donations:
        description: Shows who donated server recently with
    verify:
        description: Verifies your Minecraft account
    ai:
        description: Generates an AI response based on the prompt